root: true
env:
  es2021: true
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
  sourceType: module
plugins:
  - 'prettier'
  - '@typescript-eslint'
extends:
  - 'prettier'
  - 'plugin:@typescript-eslint/recommended'
  - 'htmlacademy/node'
