version: '3.9'
services:
  db_mongo:
    image: mongo:4.2
    restart: always
    container_name: six_cities_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_PASSWORD}
    ports:
      - ${DB_MONGO_PORT}:27017
    volumes:
      - six_cities_data:/data/db_mongo

  db_ui:
    image: mongo-express:1.0.2-20
    restart: always
    container_name: six_cities_mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_MONGO_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_MONGO_USER}:${DB_MONGO_PASSWORD}@db_mongo:${DB_MONGO_PORT}/

volumes:
  six_cities_data:
